@extends(config('version-updater.layout'))

@push('title'){{ $title }}@endpush

@section('content')
<style>
.ashik-update{min-height:calc(100vh - 80px);padding:34px;background:#f7f9fc;color:#172b4d}.ashik-shell{max-width:1080px;margin:auto}.ashik-hero{border-radius:24px;padding:34px 38px;color:#fff;background:linear-gradient(120deg,#155eef,#6941c6);box-shadow:0 18px 42px #34405426;display:flex;align-items:center;justify-content:space-between;gap:24px}.ashik-hero h1{margin:0 0 8px;font-size:30px;font-weight:800}.ashik-hero p{margin:0;color:#e0eaff}.ashik-mark{height:62px;width:62px;border:1px solid #ffffff55;border-radius:18px;background:#ffffff1f;display:grid;place-items:center;font-size:25px;font-weight:800}.ashik-alert{margin:22px 0;padding:15px 18px;border-radius:12px}.ashik-success{background:#ecfdf3;color:#027a48}.ashik-error{background:#fef3f2;color:#b42318}.ashik-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:22px;margin-top:22px}.ashik-card{background:#fff;border:1px solid #eaecf0;border-radius:18px;padding:26px;box-shadow:0 8px 24px #1018280b}.ashik-card h3{margin:0 0 20px;font-size:18px}.ashik-version{display:flex;align-items:center;gap:20px}.ashik-version-box{flex:1;background:#f8f9fc;border-radius:14px;padding:18px}.ashik-version-box small{display:block;color:#667085;margin-bottom:7px}.ashik-version-box strong{font-size:25px}.ashik-arrow{font-size:24px;color:#98a2b3}.ashik-ready{color:#039855}.ashik-pending{color:#b54708}.ashik-drop{border:1.5px dashed #98a2b3;border-radius:14px;text-align:center;padding:28px 18px;background:#fcfcfd}.ashik-drop input{display:block;max-width:100%;margin:14px auto}.ashik-btn{border:0;border-radius:9px;padding:11px 18px;font-weight:700;cursor:pointer}.ashik-primary{background:#155eef;color:#fff}.ashik-green{background:#039855;color:#fff}.ashik-red{background:#d92d20;color:#fff}.ashik-actions{display:flex;gap:10px;flex-wrap:wrap}.ashik-note{font-size:13px;color:#667085;line-height:1.6}.ashik-details{display:grid;grid-template-columns:1fr 1fr;gap:12px}.ashik-detail{padding:14px;border:1px solid #eaecf0;border-radius:12px}.ashik-detail span{display:block;color:#667085;font-size:12px;margin-bottom:5px}.ashik-detail b{font-size:15px}
@media(max-width:760px){.ashik-update{padding:18px}.ashik-hero{padding:25px;align-items:flex-start}.ashik-mark{display:none}.ashik-grid{grid-template-columns:1fr}.ashik-version{gap:8px}.ashik-version-box strong{font-size:20px}.ashik-details{grid-template-columns:1fr}}
</style>
<div class="ashik-update"><div class="ashik-shell">
    <div class="ashik-hero"><div><h1>{{ $title }}</h1><p>Secure, local and fully controlled application updates.</p></div><div class="ashik-mark">A</div></div>
    @if(session('success'))<div class="ashik-alert ashik-success">✓ {{ session('success') }}</div>@endif
    @if(session('error'))<div class="ashik-alert ashik-error">{{ session('error') }}</div>@endif
    @if($errors->any())<div class="ashik-alert ashik-error">{{ $errors->first() }}</div>@endif
    <div class="ashik-grid">
        <div class="ashik-card"><h3>Version status</h3><div class="ashik-version"><div class="ashik-version-box"><small>Installed version</small><strong>{{ $manager->currentVersion() }}</strong><br><span class="ashik-note">Build {{ $manager->currentBuild() }}</span></div><div class="ashik-arrow">→</div><div class="ashik-version-box"><small>Application release</small><strong>{{ $manager->latestVersion() }}</strong><br><span class="ashik-note">Build {{ $manager->latestBuild() }}</span></div></div><p class="{{ $manager->currentBuild() < $manager->latestBuild() ? 'ashik-pending' : 'ashik-ready' }}" style="margin:22px 0 0;font-weight:700">{{ $manager->currentBuild() < $manager->latestBuild() ? '● Update available' : '● Your system is up to date' }}</p></div>
        <div class="ashik-card"><h3>System information</h3><div class="ashik-details"><div class="ashik-detail"><span>Framework</span><b>Laravel {{ app()->version() }}</b></div><div class="ashik-detail"><span>PHP runtime</span><b>{{ PHP_VERSION }}</b></div><div class="ashik-detail"><span>Updater</span><b>Ashik Local</b></div><div class="ashik-detail"><span>Connection</span><b class="ashik-ready">Offline safe</b></div></div></div>
    </div>
    @if($manager->currentBuild() < $manager->latestBuild())<div class="ashik-card" style="margin-top:22px"><h3>Upload release package</h3><p class="ashik-note">Upload a ZIP containing <code>update_note.json</code>. Always back up your database and files before applying a release.</p><div class="ashik-drop"><div style="font-size:30px">↑</div><b>Choose your Ashik update package</b><form method="POST" action="{{ route('ashik.version-update.upload') }}" enctype="multipart/form-data"><div><input type="file" name="update_file" accept=".zip" required></div>@csrf<button class="ashik-btn ashik-primary" type="submit">Upload package</button></form></div></div>@endif
    @if($uploaded)<div class="ashik-card" style="margin-top:22px"><h3>Package ready to install</h3><p class="ashik-note">Your package passed the upload step and is ready to be applied.</p><div class="ashik-actions"><form method="POST" action="{{ route('ashik.version-update.apply') }}">@csrf<button class="ashik-btn ashik-green" type="submit">✓ Apply update</button></form><form method="POST" action="{{ route('ashik.version-update.delete') }}">@csrf @method('DELETE')<button class="ashik-btn ashik-red" type="submit">Delete package</button></form></div></div>@endif
</div></div>
@endsection
